"""Increase ISBN length from 13 to 25

Revision ID: f7324a7c522f
Revises: b8e2210e5d68
Create Date: 2025-05-03 02:38:16.259132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7324a7c522f'
down_revision = 'b8e2210e5d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=mysql.VARCHAR(length=13),
               type_=sa.String(length=25),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.String(length=25),
               type_=mysql.VARCHAR(length=13),
               existing_nullable=True)

    # ### end Alembic commands ###
